-- =============================================
-- Setup de tablas en Supabase para RIBERASPORT
-- =============================================
-- Pegá este script en: Supabase → SQL Editor → New query → Run
-- (correrlo una sola vez)

create table if not exists proveedores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  contacto text,
  telefono text,
  email text,
  notas text,
  created_at timestamptz default now()
);

create table if not exists productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  talle text,
  color text,
  genero text,
  costo numeric not null default 0,
  precio numeric not null default 0,
  stock integer not null default 0,
  stock_min integer not null default 0,
  fecha_entrada text,
  proveedor_id bigint references proveedores(id) on delete set null,
  forma_pago_compra text,
  created_at timestamptz default now()
);

create table if not exists ventas (
  id bigint generated by default as identity primary key,
  fecha text,
  cliente text,
  producto_id bigint,
  producto_nombre text,
  cantidad integer not null default 0,
  precio numeric not null default 0,
  costo_unitario numeric not null default 0,
  costo_total numeric not null default 0,
  valor_final numeric not null default 0,
  ganancia numeric not null default 0,
  estado_pago text default 'Pago',
  forma_pago text default 'Efectivo',
  obs text,
  created_at timestamptz default now()
);

create table if not exists visitas (
  id bigint generated by default as identity primary key,
  session_id text,
  user_agent text,
  referrer text,
  created_at timestamptz default now()
);
create index if not exists visitas_created_at_idx on visitas (created_at desc);

-- Habilitar RLS y crear policies abiertas (lectura/escritura pública con anon key)
alter table productos enable row level security;
alter table ventas enable row level security;
alter table proveedores enable row level security;
alter table visitas enable row level security;

drop policy if exists "lectura publica productos" on productos;
drop policy if exists "escritura publica productos" on productos;
drop policy if exists "lectura publica ventas" on ventas;
drop policy if exists "escritura publica ventas" on ventas;
drop policy if exists "lectura publica proveedores" on proveedores;
drop policy if exists "escritura publica proveedores" on proveedores;
drop policy if exists "lectura publica visitas" on visitas;
drop policy if exists "escritura publica visitas" on visitas;

create policy "lectura publica productos" on productos for select using (true);
create policy "escritura publica productos" on productos for all using (true) with check (true);
create policy "lectura publica ventas" on ventas for select using (true);
create policy "escritura publica ventas" on ventas for all using (true) with check (true);
create policy "lectura publica proveedores" on proveedores for select using (true);
create policy "escritura publica proveedores" on proveedores for all using (true) with check (true);
create policy "lectura publica visitas" on visitas for select using (true);
-- Solo permitimos INSERT publico (no DELETE/UPDATE) para que nadie pueda borrar el log
create policy "insert publico visitas" on visitas for insert with check (true);
