-- =============================================
-- Gastos generales (ferias, publicidad, insumos, envíos)
-- =============================================
-- Pegá este script en: Supabase → SQL Editor → New query → Run
-- Es idempotente: se puede correr más de una vez sin duplicar nada.
-- Después de verificar que esté todo ok, correr supabase_gastos_limpieza.sql.

create table if not exists gastos (
  id bigint generated by default as identity primary key,
  fecha text,
  categoria text not null default 'OTROS',
  concepto text,
  monto numeric not null default 0,
  forma_pago text default 'EFECTIVO',
  obs text,
  venta_origen_id bigint, -- si vino migrado de una "venta SIN PRODUCTO", el id de esa venta
  created_at timestamptz default now()
);
alter table gastos add column if not exists venta_origen_id bigint;

alter table gastos enable row level security;

drop policy if exists "lectura publica gastos" on gastos;
drop policy if exists "escritura publica gastos" on gastos;
create policy "lectura publica gastos" on gastos for select using (true);
create policy "escritura publica gastos" on gastos for all using (true) with check (true);

-- Las ventas inactivas no se muestran ni se cuentan en el sistema, pero siguen en la base.
alter table ventas add column if not exists activa boolean not null default true;

-- Migración: copiar a gastos las "ventas SIN PRODUCTO" con monto negativo (que en
-- realidad eran gastos) y marcarlas como inactivas. NO se borran de ventas.
-- Quedan como ventas activas:
--   - las ventas sin producto con monto positivo (ej: señas)
--   - los movimientos de DUEÑOS (son compra/venta de ropa, no gastos)
insert into gastos (fecha, categoria, concepto, monto, forma_pago, venta_origen_id)
select
  v.fecha,
  case
    when upper(coalesce(v.obs, '')) like '%FERIA%' then 'FERIA'
    when upper(coalesce(v.obs, '')) like '%PUBLICIDAD%' then 'PUBLICIDAD'
    else 'INSUMOS'
  end,
  coalesce(nullif(v.obs, ''), 'SIN DETALLE'),
  -v.valor_final,
  v.forma_pago,
  v.id
from ventas v
where coalesce(v.producto_id, 0) = 0
  and v.valor_final < 0
  and upper(coalesce(v.cliente, '')) <> 'DUEÑOS'
  and not exists (select 1 from gastos g where g.venta_origen_id = v.id);

update ventas set activa = false
where id in (select venta_origen_id from gastos where venta_origen_id is not null);

-- =============================================
-- PARA DESHACER la migración (volver todo como estaba), correr solo esto:
--
--   update ventas set activa = true
--   where id in (select venta_origen_id from gastos where venta_origen_id is not null);
--   delete from gastos where venta_origen_id is not null;
-- =============================================
